### ISSUE TITLE
Plenty exceptions

### ISSUE THREAD

**Issue by Nothing4You** [Sycnex/Windows10Debloater#1]
Hi there,
I was just trying to test this script on a fresh windows 10 VM:
```
Windows 10 Professional
Version 1709 Build 16299.15
```
Log: https://gist.github.com/Nothing4You/c5f8f579c336523acd7bc2a399bd4322

**Comment by Sycnex** [comment]
Hi there!

It's something I'm currently working on. What you're seeing is primarily
Windows saying that it couldn't remove specific packages due to specific
ones, such as the .net framework, being dependent on packages it asked to
remove, and since Windows didn't allow the removal it then threw an
exception.

I'm looking to add better error handling today, and am looking to fix the
Start-Debloat Function to be more specific about the
AppXPackages/AppXProvisionedPackages to remove.

**Comment by Sycnex** [comment]
The issue where you were seeing a lot of error exceptions has been resolved. I added -ErrorAction SilentlyContinue to the end of each RemoveAppXPackage/RemoveAppXProvisionedPackage so that you won't see a ton of error exceptions. On top of that I added a verbose option so that you can see what the debloat function is trying to remove.
