### ISSUE TITLE
`Remove all bloatware` won't completely remove OneDrive

### ISSUE THREAD

**Issue by Sopor** [Sycnex/Windows10Debloater#108]
When running the `Remove all bloatware` it seems to remove part of the OneDrive, so i'm forced to run the `Uninstall OneDrive` to remove OneDrive completely. I don't understand why it won't remove the OneDrive icon in the `File Explorer`? That seems to be the only thing the `Remove all bloatware` won't remove. at least what i can see. If OneDrive is included in `Remove all bloatware` then it should remove it completely too and not leave some parts of it.

I'm using the `Windows10DebloaterGUI.ps1` and Windows Version 1809 (OS Build 17763.379)

**Comment by Tmp341** [comment]
Even though explorer is closed, it couldn't remove onedrive's some dlls. When i checked what is using them, i saw that firefox was the one (dunno why, i haven't try to open them with it).

I think it is seperate, because it is another kinda pain. I've unistalled it before, but something else (i guess office) installed it back. It is triggered by some update or an app, so it is not practical trying to remove onedrive again  with bloatwares over and over.

**Comment by Gray-0men** [comment]
One drive is not part of the remove all option because sometimes it's used in enterprise environments so it's a secondary optional option, 
I personally tried to include it with the debloat all but I do agree that it should be an optional removal instead of always getting removed with all the other apps BECAUSE it's not an "app" per se AND the removal process is a little unique in order for it to be done correctly

the fact that the debloat all isn't removing one drive isn't an issue, it's intentionally left out
