### ISSUE TITLE
Store and photos not being provisioned

### ISSUE THREAD

**Issue by a60wattfish** [Sycnex/Windows10Debloater#3]
https://github.com/Sycnex/Windows10Debloater/blob/b7b8a1d0825b24fdcc919adf003f44ba70a1d556/Windows10DebloaterSilent.ps1#L26-L27

The store and photo apps in the provisioned list aren't being checked correctly, they should be checked against packagename, rather than name like FreshPaint and WindowsCalculator are checked.

**Comment by smoonlee** [comment]
Correct me if am wrong, but if you based it on the package version as apposed to the application name, wouldn't it change with every release.

**Comment by Tezjet** [comment]
Came to request the same item. Based on my testing the the above lines of code never actually result in a true and thus the apps photos and store are removed from system. I believe the intended line in the code was to NOT remove them? Aren't we removing all except those? I changed both my lines from $_.name to $_.packagename and now the packages stay installed and sysprep doesn't complain.

The sysprep error is thrown due to the app being user provisioned but not system provisioned.

Thanks for the script!

**Comment by Sycnex** [comment]
Thank you all for catching this. This should now be resolved in the latest commit.

**Comment by abulgatz** [comment]
This still seems to be an issue, or something similar. The Store, Calculator, and Photos apps are removed from the account the script is being run from. To make sure, you may check BOTH the "name" and "packagename". I'm creating a fork to try this.

**Comment by abulgatz** [comment]
That didn't work, still removes the Store, Calculator, Photos, and Paint from the user account the script is run as.

**Comment by abulgatz** [comment]
These lines seem to restore the apps. Maybe they need to be added to the script?

```
Get-AppxPackage -allusers Microsoft.Paint3D | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
Get-AppxPackage -allusers Microsoft.WindowsCalculator | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
Get-AppxPackage -allusers Microsoft.Windows.Photos | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
```
