### ISSUE TITLE
not being able to download

### ISSUE THREAD

**Issue by Legendary21** [Sycnex/Windows10Debloater#332]

**Comment by ghost** [comment]
You can download this project from the Green "Code" button and pressing "Download Zip". Alternatively, just use this link
https://github.com/Sycnex/Windows10Debloater/archive/master.zip

Then, you should reference the [install guide](https://github.com/Sycnex/Windows10Debloater#how-to-run-the-windows10debloaterps1-and-the-windows10debloaterguips1-files) from the ReadMe.

If you are unable to download the project from the link provided, the issue is likely on the side of your browser/internet connection.
