### ISSUE TITLE
Rename Blacklist and Whitelist to Blocklist and Allowlist

### ISSUE THREAD

**Issue by LaurenAGauthier** [Sycnex/Windows10Debloater#348]
Just something the software community has been adopting lately. 👍

**Comment by dbenoy** [comment]
What a repulsive thing to say. I wish people would stop trying to introduce racial division where there isn't any.

**Comment by domsch1988** [comment]
> 
> 
> What a repulsive thing to say. I wish people would stop trying to introduce racial division where there isn't any.

I don't get why there is so much pushback on this subject. Just because it doesn't bother you personally doesn't mean it doesn't bother others. It costs literally nothing to change it, is minimal effort and is much more descriptive of what it does anyways.

No one is implying that the dev had any racial division in mind here. It's just about slowly introducing new terminology that not offensive to most people and more descriptive of the functionality. It's Zero effort and makes a lot of people that are part of minorities happy/feel better.

**Comment by Sycnex** [comment]
I can see that perhaps it would help those who are less technically inclined to better understand the list. I can make the change.

**Comment by Sycnex** [comment]
This has been done.
