### ISSUE TITLE
One Drive

### ISSUE THREAD

**Issue by jvandyman** [Sycnex/Windows10Debloater#40]
When I elect to uninstall One Drive, the script hangs. This has now been attempted on two computers with the same result. What I end up doing is rebooting the PC, running the script again, and then opting out when prompted to uninstall One Drive. Please advise and thank you for your time.

**Comment by Sycnex** [comment]
I'll check this out today.

**Comment by Sycnex** [comment]
In my testing my script was hanging on line 541 because the script did not find that the HKCR was loaded as a PSDrive. I have added code to create a new PSDrive which loads HKCR and allows it to create/modify the necessary registry keys. I believe that this fixed the issue. I cannot replicate your error anymore.

However, I have used PowerShell ISE, not VSCode.

**Comment by jvandyman** [comment]
Your time is tremendously appreciated!
Thank you again!
