### ISSUE TITLE
Some Apps Remain

### ISSUE THREAD

**Issue by Skatterbrainz** [Sycnex/Windows10Debloater#41]
Running the current master branch of Windows10SysPrepDebloater.ps1 with all of the parameters on Windows 10 x64 1803 Enterprise SKU en-us.  It's leaving two apps behind at the end: Fresh Paint and Network Speed Test.  I've run this on 5 separate machines with the same OS build and getting the same result.  Otherwise, it seems to work fine.

**Comment by Sycnex** [comment]
I was hoping that the blacklist would take care of that. I will take a look a this.

**Comment by Sycnex** [comment]
Are you sure the apps remain or are they the tiles?

**Comment by Sycnex** [comment]
After looking through my code I just realized that I have FreshPaint whitelisted so that it isn't removed. You can remove it from this line here:

Line 89 [regex]$WhitelistedApps = 'Microsoft.Paint3D|Microsoft.WindowsCalculator|Microsoft.WindowsStore|Microsoft.Windows.Photos|CanonicalGroupLimited.UbuntuonWindows|Microsoft.XboxGameCallableUI|Microsoft.XboxGamingOverlay|Microsoft.Xbox.TCUI|Microsoft.XboxGamingOverlay|Microsoft.XboxIdentityProvider|Microsoft.MicrosoftStickyNotes|Microsoft.MSPaint*'

**Comment by xsisbest** [comment]
I see you whitelist sticky notes too but it's getting removed. I noticed in the previous build that was true too but one time I did the manual script instead of the sysprep one and it was there. I wonder if the switches have anything to do with it? I utilize all 3 now in my mdt.. Debloat, stopedge and sysprep. I've installed sysprep version multiple times and sticky notes is gone all 3.

**Comment by Sycnex** [comment]
I can check the sysprep script and see what's going on with that. I thought
you were talking about the regular Windows10Debloater script itself, not
the sysprep version. I'll take a look at it today.

**Comment by xsisbest** [comment]
Yes the sysprep version seems to remove sticky notes for some reason. Thank
you so much for looking! I use this at the school I work at and it works
awesome but teachers/secretaries love their sticky notes! :D

**Comment by xsisbest** [comment]
I just noticed in your script you have sticky notes listed like this: #"*Microsoft.MicrosoftStickyNotes*"

Should it just be Microsoft.Sticky.Notes or is it Microsoft.MicrosoftStickyNotes ? I didn't know if that was just commented out either but it didn't look similar to the other apps that are white listed when it comes to the name of the app. Most have Microsoft.App.Name. 

Never mind.. I see the process on my computer and it is Microsoft.MicrosoftStickyNotes. My bad.. Just trying to help carry on :D

**Comment by Skatterbrainz** [comment]
Maybe you could add a switch to handle using a white list or just rip everything out?

**Comment by Sycnex** [comment]
There is. Basically if you choose to debloat it will rip everything out except for what is in the whitelist.

**Comment by Sycnex** [comment]
The debloat function removes everything except for what is listed in the whitelist and then if anything is accidentally removed the FixWhitelistedApps function re-adds them.

**Comment by Blu3ish** [comment]
It seems "My office" and "One note" are not uninstalled, i didnt use the -Sysprep maybe that has something to do with it? why would i use that option anyway? does turning off the store updates have anything to do with it?

**Comment by Sycnex** [comment]
The -SysPrep parameter doesn't have anything to do with those not being removed, but SysPrep is used for preparing a Windows Image that will be cloned multiple times. It's largely used in virtualization environments.

I'm just curious, what happens if you run these lines of code @Blu3ish ?

Get-AppxPackage -Name * OneNote * -AllUsers | Remove-AppxPackage
Get-AppxPackage -Name * My Office * -AllUsers | Remove-AppxPackage

P.S. there the asterisks next to OneNote and My Office are meant to be directly at the begging and end of the first and last letter but it wants to use those to make the words italic. Sorry.

**Comment by Sycnex** [comment]
Can you try the latest update and use the blacklist that I added in?

**Comment by xsisbest** [comment]
Is the blacklist a new parameter? I'm going to try this new build tomorrow first thing.

**Comment by Sycnex** [comment]
It isn't as I only added it to the Windows10Debloater.ps1 and not the
Windows10SysPrepDebloater.ps1.

However, I am happy to add it shortly, if you like.

On Oct 4, 2018 8:04 PM, "xsisbest" <notifications@github.com> wrote:

Is the blacklist a new parameter? I'm going to try this new build tomorrow
first thing.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Sycnex/Windows10Debloater/issues/41#issuecomment-427232560>,
or mute the thread

**Comment by xsisbest** [comment]
Oh no worries. I only use the sysprep version. I am trying your newest version tomorrow. I have noticed sticky notes in particular was removed on the last build. Hoping it's still there after deployment. Will post my results. As always thanks so much for all your hard work and constantly replying to the issues!

**Comment by Sycnex** [comment]
Done! New parameter is -DebloatSpecificApps.

I changed the name of the function Start-Debloat to DebloatAll, and the new function for the blacklist is DebloatBlacklist.

**Comment by xsisbest** [comment]
Does that mean I'll have to change the parameters in my MDT? I currently use - sysprep - debloat -StopEdge. 
Do I need to add - debloatall now?

**Comment by Sycnex** [comment]
Yes. The one that no longer exists is -Debloat.

It is now -DebloatAllApps which is the one that rips everything out, and
-DebloatSpecificApps utilizes the blacklist I added.

**Comment by xsisbest** [comment]
Looks like I'll also take advantage of the privacy switch as well. 
Can I add sticky notes to the whitelist and it will retain it or is it more complicated than that?  I would prefer to do the - debloatall but that's the one app I'd like to not debloat.  Also does this remove one drive as well? Didn't see that in the list of apps removed. Thanks again!

**Comment by Blu3ish** [comment]
> The -SysPrep parameter doesn't have anything to do with those not being removed, but SysPrep is used for preparing a Windows Image that will be cloned multiple times. It's largely used in virtualization environments.
> 
> I'm just curious, what happens if you run these lines of code @Blu3ish ?
> 
> Get-AppxPackage -Name * OneNote * -AllUsers | Remove-AppxPackage
> Get-AppxPackage -Name * My Office * -AllUsers | Remove-AppxPackage
> 
> P.S. there the asterisks next to OneNote and My Office are meant to be directly at the begging and end of the first and last letter but it wants to use those to make the words italic. Sorry.

Thankyou for the explanation, I copy pasted the new script and it works without a problem at all, it’s great! this should be delivered by every manufacturer as optional script to clean bloatware lol :-)

I added some lines for whitelisting some apps I actually want to keep and I was searching for a fix on the web but I couldn’t really find one.
I got those lines in to my whitelist:
(of course, more than this but that isn’t important)
'Microsoft.Microsoft.BingNews|Microsoft.BingFinance'

Get-AppxPackage -allusers Microsoft.Microsoft.BingNews | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
	Get-AppxPackage -allusers Microsoft.BingFinance | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}

Now I would like those apps to stay I tried figuring out why they are still removed while I added them to the whitelist. But What I found out after doing a clean installation of windows 10 without internet connection is that the apps are installed using the live(download) method on start menu, the same is used for the crappy ads and such.

My question is is there a solution to install those apps while not having the live option enabled?

I saw this website explaining how to remove and how to re add apps: https://www.pdq.com/blog/removing-windows-10-apps-with-powershell/
But i think they have never been on the system to begin with since they have to be sideloaded/downloaded or how you want to call it.

It might be the same problem that pojebunny is facing: The Script removes EVERYTHING even though some apps have been removed from the script.
I would really apricate it if you would take a look at it.


Kind regards

Rowan Janse

**Comment by xsisbest** [comment]
So I ran the updated script but I think my parameter was set wrong. I used -DebloatAllApps and I see several things like Feedback Hub, Solitaire,Xbox, Groove Music etc still installed. I am going to try and re-run it again but just to make sure and change it to -DebloatAll..
Should this be what my parameters looks like in MDT to invoke the switches? (see link) Not sure I needed the -Privacy one but I just want to make sure I'm coding this correctly. Thank you for the help!
https://drive.google.com/file/d/11ZCG25WP3bPzfN2Q30SOo5x7huw3G1T8/view?usp=sharing

**Comment by xyipher** [comment]
I just ran, as admin,  Windows10SysPrepDebloater.ps1 -DebloatAllApps -SysPep -StopEdgePDF -Privacy

I'm noticing there are a few Apps being left behind: Network Speed Test, Sway, Microsoft News
Picture:  
![startmenu](https://user-images.githubusercontent.com/24981941/46556324-2d485000-c89b-11e8-8171-2efd9a4c1d84.png)

On an untouched machine prior to running that script I listed all the AppxPackages and do not see those three apps in the list

Excel Sheet of AppxPackage Apps: 
[Get-AppxPackage.xlsx](https://github.com/Sycnex/Windows10Debloater/files/2452030/Get-AppxPackage.xlsx)

Windows Info:
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134

**Comment by xsisbest** [comment]
I have Feedback hub, Solitaire, Xbox, My Office, One note and Skype. There are a few others too that I wasn't sure if they were removed before or not like alarms and clocks.. not a big deal on that though.
Oddly enough I don't have Sway, SpeedTest or Microsoft news. I used all the same parameters but I used -Sysprep -DebloatAll - StopEdgePDF - Privacy.
I also don't know what the StopEdgePDF is good for as I install Adobe Reader and set it as the default using it's own parameters and still Edge takes over as default PDF reader. Is there a way to set it as Adobe Acrobat Reader in the script somehow?

**Comment by xsisbest** [comment]
So after working on this quite a bit today, I've come to a couple conclusions. 
The first was on the sysprep debloater, under the Whitelisted apps your parameter was wrong. It says -DebloatApps but it should be DebloatAllApps:

Function FixWhitelistedApps {

    Param([switch]$DebloatApps, [switch]$DebloatSpecificApps, [switch]$SysPrep)

Once I changed it to DebloatAllApps it was whitelisting everything you've added and a few more that I added like sticky notes and voice recorder.

I also found that in order for it to remove everything, even if you use the DebloatAllApps parameter, you still have to run DebloatSpecificApps or those apps under the blacklist will still be present. Once I ran the script using all parameters, everything was gone....BUT
Only for the administrator account. When I logged into another account all the apps were there that were under the blacklist like My Office, One Note, Alarms and Clocks, Feedback Hub, Xbox etc... 
I don't know what changed from the new one but I used your older script up until recently as it removes everything.. and from every account without issue. I may end up going back to that one which was sometime around June if I recall. Anyway, that one worked flawless for me. 
I again run this during my MDT deployment so it's not theoretically being installed during sysprep. In order to use MDT properly, you need to let MDT run sysprep and create a WIM file that will be the base of your install. It's just the OS with all your configurations, settings and apps you want. Then you can customize the install using a task sequence to install other apps and scripts. That's when your script installs so I'm wondering if it's not applying to the default user hive so that it applies to all users. But your old script ran at the same time after sysprep and it worked fine so I'm a bit confused. 

I feel like I'm close... the admin account is perfect when my MDT is finished and all apps are gone using all parameters but any other accounts the blacklisted apps persist. That's the gist. Thanks again for all your hard work!

**Comment by xsisbest** [comment]
I added the updated white list apps to your old script and it now is working perfectly, removing everything I need and for all users. 
The one thing I notice right off the bat is the command in your old script for whitelistedapps,  it had some code for all users where your more recent does not. I'm thinking that is the difference in it not copying to other user accounts. 
Here is your old one with my modifications. I removed the StopEdge pdf stuff and added sticky notes and voice recorder to the whitlistedapps but other than that its the same. It also only utilizes the - SysPrep and - Debloat switches. 
https://drive.google.com/file/d/11bc6l2OJLWe8iu2b93GqAf1iiDBu3O71/view?usp=sharing

**Comment by Sycnex** [comment]
Hey wow, thank you for all of your hard work! You single-handedly fixed this. I was going to hop on today to take a look but I see that you have already done that. Great work! I went ahead and updated the script with the version you provided and it indeed does work properly. Sorry about the bad version!

I went ahead and credited you in the comments and will be adding you to the Credit section in the ReadMe :)

I'm happy everything is working for you!

**Comment by xsisbest** [comment]
Thank you very much for the compliment but I don't feel I did anything really except add "Apps" to the end of one line of code but this was all your original code. I just modified it to my liking. 
Just so other users know if you come across this thread, you can add any app into the whitelist and it should keep it. Look under Sycnex Windows10Debloater.ps1 for a list of all the different apps and just add them in 2 spots in this script. One is line 40:

[regex]$WhitelistedApps = 'Microsoft.Paint3D|Microsoft.MSPaint|Microsoft.WindowsCalculator|Microsoft.WindowsStore|Microsoft.MicrosoftStickyNotes|Microsoft.WindowsSoundRecorder|Microsoft.Windows.Photos|CanonicalGroupLimited.UbuntuonWindows'

If you want an app whitelisted just smash it in between one of these like I did for Sticky Notes and Windows sound recorder. Alternatively remove them if you don't want any of them. Just put the Appname and a | with no spaces.

The next spot is line 190. Just Add the app name in between another and add a comma... easy

Then starting on line 193 just copy one of the other whitelisted apps code, preferably not the last one as it has to }} brackets. Copy one at the beginning or whatever and then just alter the name to match the one you wanted to whitelist, or again remove. As you can see I added Sticky Notes and Sound recorder and all I did was change the name of one like Microsoft.Paint3D etc.. 

Hopefully this works for everyone else cause I love this script. It makes all the headaches of Windows 10 go away for me. I appreciate your amazing work and will most definitely let everyone know about your work!

**Comment by xyipher** [comment]
Got an error on Line 29: & sc config InstallService start=disabled

I changed the command and it works for me now

 **& Set-Service -Name InstallService -StartupType Disabled**

**Comment by xyipher** [comment]
Line 42, I also got an error. Windows Enterprise Build 1803.

A reboot and re-run of the script was required for it to work properly as suggested here: 
![line 42 error](https://user-images.githubusercontent.com/24981941/46621968-d67e8880-cadd-11e8-949e-dd8ade9c0f00.png)

FIXED: Re-running line 41 fixes the issue of having to reboot.

Proposed this and fix above. No errors now when running on Windows 10 Enterprise 1803

**Comment by Sycnex** [comment]
Thank you all for the help and fixes!

**Comment by Sycnex** [comment]
Do you guys have any suggestions for what should go into the script next?

**Comment by Skatterbrainz** [comment]
Does your script provide a grid view option for selecting individual packages to remove?

**Comment by xsisbest** [comment]
I don't know the slightest things about Powershell but if you look at though normal debloater and the sysprep version you can find all the names of the apps and then adjust each script to remove the apps or add the apps to the whitelist that you need or don't need. Just a little bit of studying the files and looking for that whitelist will help you understand which apps and names you need to add a remove for your preference. Here is a list of most the apps as found in the Windows10Debloater script. Just add these to your whitelist sections. (or remove)

"Microsoft.BingNews"
        "Microsoft.DesktopAppInstaller"
        "Microsoft.GetHelp"
        "Microsoft.Getstarted"
        "Microsoft.Messaging"
        "Microsoft.Microsoft3DViewer"
        "Microsoft.MicrosoftOfficeHub"
        "Microsoft.MicrosoftSolitaireCollection"
        "Microsoft.NetworkSpeedTest"
        "Microsoft.Office.OneNote"
        "Microsoft.Office.Sway"
        "Microsoft.OneConnect"
        "Microsoft.People"
        "Microsoft.Print3D"
        "Microsoft.RemoteDesktop"
        "Microsoft.SkypeApp"
        "Microsoft.StorePurchaseApp"
        "Microsoft.WindowsAlarms"
        "Microsoft.WindowsCamera"
        "microsoft.windowscommunicationsapps"
        "Microsoft.WindowsFeedbackHub"
        "Microsoft.WindowsMaps"
        "Microsoft.WindowsSoundRecorder"
        "Microsoft.Xbox.TCUI"
        "Microsoft.XboxApp"
        "Microsoft.XboxGameOverlay"
        "Microsoft.XboxIdentityProvider"
        "Microsoft.XboxSpeechToTextOverlay"
        "Microsoft.ZuneMusic"
        "Microsoft.ZuneVideo"

**Comment by Sycnex** [comment]
@Skatterbrainz Not yet but that is a fantastic suggestion. I found a nice method of doing this. It will take me time since I need to find some time to sit down and work on it.

**Comment by suchislife801** [comment]
Greetings and thank you for the amazing script.

If you haven't yet considered, I would like to propose a C# GUI to call smaller, targeted scripts that comprise the whole. These could be options to choose from in the UI making it much more intuitive(if this is of interest).

Another idea would be a script generator comprised of these same options - if all checked - while in the other hand, the user can customize by checking only the options they would like available in the script. This version could be implemented in JS for all platforms.

**Comment by Sycnex** [comment]
Absolutely! I'm accepting any suggestions. I actually have a PowerShell GUI
that I have created in my test/development branch. Feel free to take a
look! And absolutely feel free to work on a C# GUI :) the more the merrier!

**Comment by Sycnex** [comment]
Here is the GUI I am currently working on. I am hoping to have some free time this weekend to continue work on it:

https://github.com/Sycnex/Windows10Debloater/blob/Testing/Develop/Windows10DebloaterGUI

**Comment by marcthestrong** [comment]
If its ok, I can fork this. Im pretty comfortable with building in VB

**Comment by Sycnex** [comment]
Yes of course. Feel free to do as you wish.

**Comment by Sycnex** [comment]
Hi all, I am happy to report that there is now a GUI Application available! It is called Windows10DebloaterGUI.ps1. Please feel free to test and use it and let me know any results. It works great on my end with testing.

**Comment by Sycnex** [comment]
Also, can I close this issue?

@Skatterbrainz

**Comment by xsisbest** [comment]
Fantastic! Can't wait to give it a go! As long as closing the thread doesn't delete it :D

**Comment by Sycnex** [comment]
@xsisbest Let me know what you like and dislike about it :) And closing it doesn't delete it, don't worry haha. We can always come back to it and reopen it.
