### ISSUE TITLE
Add a switch or variable to make the script run silently

### ISSUE THREAD

**Issue by a60wattfish** [Sycnex/Windows10Debloater#5]
Could you add a switch to the script (and/or a variable at the start of the file) that can be used to make the script run silently so it can be run unattended/as an MDT task?

My thoughts on this are making it so the switch would be detected just before the first prompt about enabling System Restore Functionality, and if the user does want it to be silent, just run Start-Debloat,  Remove-Keys, Protect-Privacy and then end the script.

**Comment by Sycnex** [comment]
Fantastic suggestion. I'll add this in the next commit!

**Comment by Sycnex** [comment]
Please check the new file I uploaded called "Windows10DebloaterSilent.ps1".

There is a switch parameter which runs Start-Debloat, Remove-Keys, Protect-Privacy, and Stop-EdgePDF silently, without any user interaction.

I added the Stop-EdgePDF function since it is useful in stopping Edge from constantly changing back to being the default .PDF viewer, even if you have Adobe Reader/etc. installed. Using this function doesn't do any harm in any way.

Thank you for the suggestion!
