### ISSUE TITLE
Script Not removing apps as specified

### ISSUE THREAD

**Issue by zachsaddress** [Sycnex/Windows10Debloater#50]
Hey all, this could be complete user error, I tried to run the Windows10Debloater on one of our laptops, but it would not remove the apps as specified.

I have not edited the files and I have seen no errors when running is. 

I am just right clicking on the file and running it with PowerShell, maybe I am missing something?

**Comment by Sycnex** [comment]
Hi, you will need to open either VSCode or PowerShell ISE (or whatever ISE/IDE you use) as an Administrator and then you will need to run the script(s) like that. You could copy and paste the code into PowerShell ISE and then run it.

Otherwise, after downloading the files, you can place them wherever you like in your machine, right click the files and hit Properties --> make sure the file is UNBLOCKED and then you can open the file in VSCode and run it that way (as an Administrator).

**Comment by Sycnex** [comment]
Can you try the latest update and let me know the results? I added a blacklist and perhaps this will better suite you. Just hit Yes and then No.

**Comment by Sycnex** [comment]
@zachsaddress Any progress with the latest updates?

**Comment by finxy** [comment]
I don´t know if it is related but I think I might have found an issue. In the file Windows10Debloater.ps1 in line 101 and 102 there seems to be a wrong variable name: $App. I assume it is supposed to be $Bloat although I might be missing something.

**Comment by Sycnex** [comment]
@finxy This is now fixed :)

**Comment by finxy** [comment]
What about the $App in line 102?
-finxy
