### ISSUE TITLE
I don't see a ZIP file

### ISSUE THREAD

**Issue by helmanfrow** [Sycnex/Windows10Debloater#532]
The instructions say to download the .zip file on the project main page but I don't see one.

**Comment by tu5alum** [comment]
https://github.com/Sycnex/Windows10Debloater
<img width="689" alt="image" src="https://user-images.githubusercontent.com/45538118/190929872-466e07f6-7547-4f6e-ba5d-4ad9f69e5928.png">

**Comment by helmanfrow** [comment]
Ahhh...!

**Comment by tort-oise** [comment]
This issue is just dumb altogether, stemming from not knowing how GitHub inherently works. Kindly close this, if you would be so kind.

**Comment by tu5alum** [comment]
> This issue is just dumb altogether, stemming from not knowing how GitHub inherently works. Kindly close this, if you would be so kind.

I stumbled across this problem as well in my first days, because releases (if used) are easier to spot.
People interested in this tool may visit github for the first time (although @helmanfrow forked a repo a few month ago).

Maybe this could be made more clear in the readme for people who are new to github.

**Comment by helmanfrow** [comment]
Now I know.

**Comment by helmanfrow** [comment]
I'm not entirely new to GitHub. I visit and download releases here quite frequently. I probably even knew that you could download a repository as a ZIP file but forgot as I almost never download a whole repository.
