### ISSUE TITLE
Windows10SysPrepDebloater vs Windows10Debloater and blacklist questions (GUI)

### ISSUE THREAD

**Issue by WurstCommander** [Sycnex/Windows10Debloater#69]
Hi,

I read the readme, but some thing weren't really clear for me.

I guess Windows10Debloater.ps1 is the non-silent version with questions through the debloating-process, and Windows10SysPrepDebloater.ps1 is the silent version with parameters.

- What happens if I start Windows10SysPrepDebloater.ps1 without parameters? all three are active? because I could start it without any parameters.

And the variant with the GUI, I searched for "blacklist" in the whole readme, no mention, so I have to ask (sorry).

What is the difference between:
- "Remove All Bloatware"
vs
- "Remove All Bloatware without Blacklist?"
Shouldn't this be the same?

And "Remove Bloatware With Blacklist", where can I see/change this Blacklist?

Why is removing the Regkeys important? The app files seem to be gone, so the Regkeys should be orphans.

Thank you for your time and help.

**Comment by Sycnex** [comment]
1) What happens if I start Windows10SysPrepDebloater.ps1 without parameters? all three are active? because I could start it without any parameters.

After investigating, you're correct. I am going to rewrite the parameters and make them function how they should. Right now it appears that they all run, regardless. Thank you for catching this.

2) Remove all bloatware - This uses both of the following functions - DebloatBlacklist and DebloatAll. The DebloatAll function which uses a whitelist will remove any appxpackages/appxprovisionedpackages that aren't whitelisted. The DebloatBlacklist function should theoretically remove anything possibly missed by the DebloatAll function. I also implemented this per a feature request. 

3) Remove All Bloatware without Blacklist - This only uses the DebloatAll function.

4) You can find this blacklist in the -DebloatBlacklist function, starting on line 244.

5) I remove the regkeys just because they exist after the appxpackages/appxprovisionedpackages are removed. Other than that there really is no reason. They do get repopulated I believe when the Windows Apps are reinstalled. 

You're most welcome! Thanks for asking questions. I will be updating my readme.
