### ISSUE TITLE
Microsoft Store

### ISSUE THREAD

**Issue by hanthor** [Sycnex/Windows10Debloater#7]
The name of the Store has change, and this script will uninstall it in 1709

**Comment by Sycnex** [comment]
Thanks for the information. Do you know what the new name of the Package is?

I'll investigate in the meantime.

**Comment by a60wattfish** [comment]
I've just come across this. The store name hasn't changed, but you changed the way you whitelist a few of the items. You previously checked against $_.name and $_.packagename, which worked but now checking against $_.AppxPackage and $_.AppxProvisionedPackage, which doesn't.

**Comment by Sycnex** [comment]
Thank you. This is now fixed. 

I changed back the $_.name and $_.packagename portions of my Start-Debloat function from $_.AppxPackage and $_.AppxProvisionedPackage since they weren't uninstalling almost any bloatware, and they were uninstalling important Apps such as Store and Calculator (it was an amateur mistake).

I am still learning!
