### ISSUE TITLE
Several games and junk left over

### ISSUE THREAD

**Issue by zone117x** [Sycnex/Windows10Debloater#75]
Fresh install of latest Windows 10 pro iso and ran all Windows updates. 
Then ran this script using the default options. Rebooted, and opening the start menu shows a lot of junk still

![image](https://user-images.githubusercontent.com/1447546/50842227-3f230e80-1334-11e9-9eb3-e1bee026533f.png)

**Comment by smoonlee** [comment]
If you create a new profile you won't get that, its because its existing

**Comment by Sycnex** [comment]
@smoonlee is correct. It's really hit or miss on existing profiles but works great when used before creating now profiles.

**Comment by suchislife801** [comment]
Ok. So, just to clarify, after a fresh install of Windows 10 Pro, I should abandon the first account created during setup. Then I should create a separate and local windows 10 pro user account. Then from within this new account, I should run your script. Is this correct?

**Comment by Sycnex** [comment]
You don't need to abandon the first account created. The first account created can be used to run the script and then you can create the new profile afterwards. Then you can login to that account and you shouldn't see any bloat.

However, I'd like to see why running the script on your profile doesn't remove the bloat in the first place. Can you please provide me the transaction log within C:\Temp\Windows10Debloater location please?

**Comment by Gray-0men** [comment]
I've always noticed this when I run the script, even on my old project that I merged with this one a while back. I personally run this debloat on every Win10 machine I remote into that's at a clients office and I've noticed itll skip over SOME apps (mostly candy crush and minecraft) when I'm doing other things on the computer.

Like if I run the script and let it do its thing it usually gets everything, but if I run the script and start doing other things like checking windows update or installing other software while the script is running in the background it will skip over and miss a few things. 

Running it once more usually does the trick but since its only a few leftover apps I just right click and uninstall.

**Comment by Sycnex** [comment]
Can you all run the new updated script and tell me how it works out for you?

**Comment by Sycnex** [comment]
Has anyone had a chance to try the new update?

**Comment by Sycnex** [comment]
I am going to close this for the time being. Feel free to reopen it.

**Comment by pyksid** [comment]
Hi @Sycnex,

Same problem, some bloatwares are always here after "Remove all bloatwares" from your software.

How can I help?

**Comment by smoonlee** [comment]
@dreamon11 you need to make a new profile and they disappear

**Comment by pyksid** [comment]
@smoonlee it's weird, why running the script doesn't remove the bloats on the current profile?

**Comment by smoonlee** [comment]
@dreamon11 it's how the appx thing does it stuff if you use it as part of a reference image you'll be fine

**Comment by Gray-0men** [comment]
You'll notice some apps aren't actually installed on the machine and that there's just this option to unpin them off the start menu. If you're noticing the apps still in the start menu where you can right click and select "uninstall" then try running the script one more time but don't do anything else in the background, I noticed that running windows update or uninstalling other stuff while letting this run will cause some apps to get skipped by the script.

Remember with **some** windows programs you can't install 2 things at the same time and you can't uninstall 2 things at the same time so when something else (windows update, uninstall program) is doing an uninstall/install while the script is running it'll cause the script to skip whatever it was about to attempt to uninstall so it can do that "update" or "uninstall"

I run this script daily on new installs of Win10, I also have a forked version that I'm trying to get merged over if you want to clone a copy and test it out. Less hangs and less errors with a couple more features.

I also noticed some apps are actually removed and doing a reboot of the computer will show them gone, this is where it sometimes looks like the apps aren't getting removed where they're still in the start menu. 
Example: I had candy crush still in the start menu along with Dolby audio but instead of right clicking and selecting uninstall (that option was still there after running the script) I decided to reboot first and was going to do it after the fresh reboot but after the reboot they were gone even though just before the reboot it gave me the option to uninstall. I guess they queue up to uninstall..?

again check out my fork, I have it skipping the apps that are already flagged as non-removable by the system to help with the hanging since they get skipping regardless.
