### ISSUE TITLE
It seems to have removed Slack from my machine

### ISSUE THREAD

**Issue by tolache** [Sycnex/Windows10Debloater#83]
Is that by design?

**Comment by Sycnex** [comment]
Hi, it isn’t specifically designed to remove slack or discord or any IM applications. I’m happy to add them to the whitelist so that they won’t be removed if you run it again. 

I was thinking about creating a function that will kind of scan your machine and tell you what might be removed and ask if you want to do a system restore

**Comment by tolache** [comment]
Thanks for explaining!

**Comment by Sycnex** [comment]
I added Slack to the whitelist.
